<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <?php
        echo $this->headTitle().PHP_EOL;
        $this->jQuery()->enable()->uiEnable();
        echo $this->jQuery()
            ->addStylesheet($this->baseUrl().'/css/style.css');
    ?>
    <script type="text/javascript">
        $(function() {
            $('#dialog-message-box').dialog({modal:true});
        });
    </script>
</head>
<body>
    <div id="content">
    <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>
